### ISSUE TITLE
Proposal: Re-format Weekly "All Hands" around scheduled presentations

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/tm#636]
**Proposal**: Switch the format of the weekly calls on Monday to focus on 1-2 pre-scheduled presentations, demos or discussions. Set the schedule 6-8 weeks in advance, so we can advertise a calendar of who will be presenting and what will be covered.

Structure/Timing for each call: (30 minutes total)
- 15 minutes presentation
- 5 minutes Q&A
- 5 minutes announcements

**Examples of topics we could cover**:
- @nayafia talking about open source funding models
- @pgte talking about peer*, giving an update on past work and a preview of upcoming work
- @meiqimichelle talking about UX research and user-oriented design, or telling stories about working at 18F
- @lidel giving an update about Web Browser work
- @olizilla presenting the new designs for IPFS WebUI
 
**Rationale**:
- The amount of projects has gotten too large to do a realistic sync across all the teams every week (we haven't done that in over a year)
- This isn't really an "All Hands" -- we've never had more than 30 people on the call, despite the fact that there are hundreds of people engaged with IPFS & libp2p, with 40-70 people playing active roles in pushing the ecosystem forward

**Comment by diasdavid** [comment]
I'm all in for this new format!

**Comment by mikeal** [comment]
Can we also find a way for people to request presentations on specific topics?

This would be useful for people in the community, especially new people.

**Comment by djdv** [comment]
>Define how people can propose a presentation, including a request for someone else to present on something

Would a section under https://discuss.ipfs.io/ be a good place for this?
People could write up drafts, receive feedback, and ask for thing things such as a stand-in presenter, within a thread. These could then be reviewed, scheduled around, tagged and archived.

In addition, we could have a thread for community suggestions/questions, that could serve as a place for what @mikeal is saying.

A community poll might be useful to consider here as well, for example: http://poal.me/bb5jia

**Comment by lidel** [comment]
> Would a section under https://discuss.ipfs.io/ be a good place for this?

I suspect using community forum may have an added value of bringing new people to these calls. I remember talking to at least two people at DWeb/LabDay and they were not aware it happens every week.

ps. Discourse supports polls natively:
https://meta.discourse.org/t/how-to-create-polls/77548?u=lidel

**Comment by Mr0grog** [comment]
> Discourse supports polls natively 👌

Oh, nice. I like using the discuss forum for this. We should also make sure to advertise it at the start and end of the meetings.

We could probably have a category for the all hands call and pin the agenda/poll for the upcoming call. Not sure if proposals are better handled as discussion on a particular week's call or if each one should be a new topic.

> possibly set notetakers in this schedule too

Agree this is important — we probably still need notetakers here, and because the call will be less of an open discussion, there’s not as much room to ask for a volunteer and wait around until someone raises their hand (not that we wouldn’t benefit from *already* doing this anyway).

**Comment by flyingzumwalt** [comment]
Is there any reason why that spreadsheet should not be publicly viewable? If everyone agrees, I can switch it so anyone with the link can view.

**Comment by Mr0grog** [comment]
Have we floated this idea by all the people whose names are on it? Otherwise it might feel to them like they just got volunteered if you make this public.

**Comment by flyingzumwalt** [comment]
Based on discussion on today's all hands, we won't have the bandwidth to make this switch until mid-September. Once @mikeal has finished hiring a community engineer he will drive this format switch and then hand it off to someone else.

**Comment by flyingzumwalt** [comment]
I'm very eager to make this switch. The Community Manager is starting October 1st and the first Community Engineer is starting October 8th. I suspect we will wait for them to arrive before we proceed.

**Comment by mikeal** [comment]
Let's plan on the Community Engineer leading this, we can sync her first week in Glasgow about it.

**Comment by pkafei** [comment]
We can set up a slack channel dedicated to community call presentations. The #community-calls channel will act as a space where the internal team can:

a. make presentation suggestions
b. access spreadsheet of upcoming presentations
c. [volunteer to present](https://docs.google.com/spreadsheets/d/1V9cUy_1qTzlQ6j5kcTPiFGkKtHK5WkxESs1ysj2FNXA/edit?pli=1#gid=1007839740)

The larger community can suggest topics in the Youtube comment section or on #ipfs irc.

**Comment by Stebalien** [comment]
> We can set up a slack channel dedicated to community call presentations. The #community-calls channel will act as a space where the internal team can:

We've pushed back on internal IPFS slack channels in the past to avoid excluding the wider community. We have quite a few very active community members *not* on slack who will likely want to give presentations and be actively involved in this process.

I'd also encourage YouTube viewers to make their proposals on GitHub, instead of YouTube. YouTube is designed for one-to-many/many-to-one communication so I'm worried this will encourage a community with a user/dev (consumer/maker) relationship rather than a participatory community.

What about issues? That is:

1. Anyone can create an issue proposing a topic.
2. Schedule presentations in per-meeting scheduling issues.

Presentations can be discussed in IRC but decisions/proposals will have to land somewhere more permanent.

**Comment by pkafei** [comment]
We could create a Github repo for community calls and schedule the presentations in the issues section. After each presentation, we'll distribute the link to Github community calls repo and everyone can write which presentations they want to see in the future.

Alternatively, we can create a "Community Call" channel in discuss.ipfs.io and handle the scheduling there.

**Comment by Stebalien** [comment]
Doing everything in discuss sounds like a great idea.

**Comment by momack2** [comment]
I really like the idea of a public sheet (or just a table in the notes doc for people to sign up in advance) where we can schedule presentation items and the discuss list for incoming proposals/etc. I think the call organizer will need to explicitly source interesting topics from the community and the team and follow up that folks are still available - either by pinging ipfs working group captains for any new interesting work going on (maybe grab ideas off the weekly newsletter?), or by reaching out to community members and explicitly asking them to present via discuss. Managing that schedule will be work for the organizer, so let's optimize the comms and make it as lightweight as possible. =]

**Comment by pkafei** [comment]
I think sourcing topics is a great idea, and the weekly newsletter or even github issues is a good place to find ideas.

**Comment by pkafei** [comment]
FYI, we are beginning the process of revamping the IPFS All Hands on Meeting. In the next several days @flyingzumwalt and I will be sending you emails and asking you to present! https://docs.google.com/spreadsheets/d/1V9cUy_1qTzlQ6j5kcTPiFGkKtHK5WkxESs1ysj2FNXA/edit?disco=AAAACVhMe1M&ts=5bd7698a#gid=113886779

**Comment by flyingzumwalt** [comment]
@pkafei if people want to present something, how can they sign up? Should they email you? Should they comment here? Should they add their presentation to the spreadsheet? Do you want to set up a google form that they can fill out?

**Comment by diasdavid** [comment]
Update of this Proposal on #737

**Comment by diasdavid** [comment]
Now there is a PR to (document and) upgrade the format -- https://github.com/ipfs/tm/pull/739

Thank you @pkafei! Let's continue the chat there :)
