### ISSUE TITLE
All Hands Call November 5, 2018 

### ISSUE THREAD

**Issue by pkafei** [ipfs/tm#736]
# Agenda and Notes

Please add your agenda items before the call.

Endeavour      | Moderator            | Notetaker | Time (PST - UTC - CET) | Pad
:------------: | :-------------: | :-------: | :--------------------: | :----:
All Hands Call | @pkafei     | TBD  | 9:00 **17:00** 18:00  | [agenda and notes](https://docs.google.com/document/d/1WHyIZhBo2eEgYXlZ5HLHg6a6ZWTH3tV848sWkYBJjJA/edit#heading=h.a8ahtmbxx516)

Zoom link for joining the call: https://protocol.zoom.us/j/443621844

**Comment by diasdavid** [comment]
@pkafei when opening this issue, can you also create the placeholder for meeting agenda and notes? It will encourage everyone to add agenda items in advance.

I've added it for this turn https://docs.google.com/document/d/1WHyIZhBo2eEgYXlZ5HLHg6a6ZWTH3tV848sWkYBJjJA/edit#heading=h.1ypy0qid4g02

**Comment by diasdavid** [comment]
@pkafei yes please :D
