### ISSUE TITLE
⚡️IPFS ALL Hands On Call Revamped⚡️

### ISSUE THREAD

**Issue by pkafei** [ipfs/tm#737]
### IPFS Hands on Meeting

![](https://media.giphy.com/media/JFawGLFMCJNDi/giphy.gif)

## The Dream

For the past couple of months, we have been discussing revamping the IPFS ALL HANDS meetings. If you want more context, please see issue https://github.com/ipfs/pm/issues/636. 

We want the IPFS hands-on meeting act as a space where we can showcase all of our hardwork and game changing projects.The IPFS meetings give viewers a taste of some of the problems we are tackling.

## What's in it for you? 😺

Fame. Oh, and the chance to practice public speaking skills. Think of it as a [Toast Masters](https://www.toastmasters.org/) for the IPFS crowd. Below are some public speaking resources.

* [How to be a better speaker at tech conferences – Nick Heiner – Medium](https://medium.com/@nickheiner/how-to-be-a-better-speaker-at-tech-conferences-c441abc8d28b)
* [11 Top Tips for a Successful Technical Presentation - Scott Hanselman](https://www.hanselman.com/blog/11TopTipsForASuccessfulTechnicalPresentation.aspx)
* [10 Tips for Improving Your Public Speaking Skills \| Harvard Professional Development | Harvard DCE](https://www.extension.harvard.edu/professional-development/blog/10-tips-improving-your-public-speaking-skills)

## The Format

Every month we will have:

* One 15 minute lightening talk (1x per month)
* Three 5 minute talks (3x per month)

In total we will have a talk every Monday. The times for the talks are:

| Time (PST - UTC -CET ) |
---|
9:00 **16:00** 18:00 |

If you have a talk you want to give, [sign up here](https://docs.google.com/spreadsheets/d/1XRB2QsPzCPLPOErKvDZfOKK3CMohI9t_QKNdztYMlK0/edit#gid=350755898) **or** please email me at portia @ protocol labs dot com.

 ![](https://res.cloudinary.com/blockchain-side-hustle/image/upload/v1541176158/ipfs_crew_xzbhxr.png)
 
 
 
 ### 🥁November Scheduled Talks🥁
 

| November 5th            | November 12th           | November 19th          | November 26th          |
| ------------------------|------------------------|------------------------|-------------------------|
| "Intro to Textile App" Sander Pick | TBD         |     TBD                |    TBD                  |
|

**Comment by diasdavid** [comment]
Now that there is a PR to (document and) upgrade the format -- https://github.com/ipfs/tm/pull/739 -- let's continue the review there.

Thank you @pkafei for creating this ! :)
